apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mibanco-app-ingress
  labels:
    app: mibanco-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: mibanco-app-service
            port:
              number: 80
        path: /
        pathType: Prefix