name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: test-app

jobs:
  ci_job:
    runs-on: ubuntu-latest
    env:
      PORT: 3000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install


  build_and_push:
    needs: ci_job
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          severity: CRITICAL
          exit-code: "1"
          ignore-unfixed: true
          output: trivy-results.json
          format: json

      - name: Check for HIGH or CRITICAL vulnerabilities
        shell: bash
        run: |
          count=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity == "HIGH" or .Severity == "CRITICAL")] | length' trivy-results.json)

          echo "Found $count HIGH/CRITICAL vulnerabilities"

          if [ "$count" -gt 0 ]; then
            echo "HIGH/CRITICAL vulnerabilities detected."
            jq '.Results[].Vulnerabilities[]? | select(.Severity == "HIGH" or .Severity == "CRITICAL")' trivy-results.json
            exit 1
          fi

          echo "No HIGH or CRITICAL vulnerabilities found."
